### ISSUE TITLE
Understandig how the face detection works

### ISSUE THREAD

**Issue by kaktuseis** [smahesh29/Gender-and-Age-Detection#3]
Hi, the age and gender detection works good, thanks for sharing!
I want to understand how the face detection works. 
Can you tell me if you use Single Shot detector or something else?

**Comment by smahesh29** [comment]
For face detection I had used pre-trained face detection model. We have a opencv_face_detector_uint8.pb file- this is a protobuf file (protocol buffer); it holds the graph definition and the trained weights of the model. We can use this to run the trained model. And while a opencv_face_detector_uint8.pb file holds the protobuf in binary format, one with the opencv_face_detector.pbtxt extension holds it in text format. These are TensorFlow files.
